= Procédures stockées
:doctype: book
:author: Nathan DEMOINERET
:hardbreaks-option:
:icons: font
:sectnums:
:font:
:toc:
:toclevels: 3
:toc-title: Parties selon le document du professeur

[[exercice_hash_d_un_produit]]
== Exercice : Hash d'un produit

[source%linenums,css,indent=0]
----
BEGIN

DECLARE concat_string VARCHAR(255);
DECLARE product_hash VARCHAR(32);

DECLARE product_count INT;
SELECT COUNT(*) INTO product_count FROM produit WHERE idProduit = product_id;

IF product_count > 0 THEN
    SET concat_string = CONCAT(product_id, product_price);
    SET product_hash = MD5(concat_string);
    SELECT product_hash AS 'Product Hash';
ELSE
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Product not found';
END IF;

END
----

[[hash_d_un_produit_avec_gestionnaire_d_erreur]]
== Hash d'un produit avec gestionnaire d'erreur

[source%linenums,css,indent=0]
----
DECLARE concat_string VARCHAR(255);
DECLARE product_hash VARCHAR(32);

-- Vérifiez si le produit existe
DECLARE product_count INT;
SELECT COUNT(*) INTO product_count FROM produit WHERE idProduit = product_id;

-- Si le produit existe, générez le hash
IF product_count > 0 THEN
    SET concat_string = CONCAT(product_id, product_price);
    SET product_hash = MD5(concat_string);
    SELECT product_hash AS 'Product Hash';
ELSE
    -- Gestionnaire d'erreur si le produit n'existe pas
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Product not found';
END IF;

END;
----

[[calcule_prix_d_un_produit_ht_vers_ttc]]
== Calcule prix d'un produit HT vers TTC

[source%linenums,css,indent=0]
----
BEGIN
    DECLARE product_price DECIMAL(10, 2);
    DECLARE ttc_price DECIMAL(10, 2);

    SELECT prix INTO product_price FROM produit WHERE idProduit = product_id;

    SET ttc_price = product_price * 1.20;
    SELECT ttc_price AS 'Price TTC';
END;
----

[[hash_de_tous_les_produits]]
== Hash de tous les produits

[source%linenums,css,indent=0]
----
BEGIN
    DECLARE product_id INT;
    DECLARE product_price DECIMAL(10, 2);
    DECLARE done INT DEFAULT 0;
    DECLARE cur CURSOR FOR SELECT idProduit, prix FROM produit;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;

    OPEN cur;
    read_loop: LOOP
        FETCH cur INTO product_id, product_price;
        IF done THEN
            LEAVE read_loop;
        END IF;

        CALL product_hash(product_id, product_price);
    END LOOP;

    CLOSE cur;
END
----

[[contrôle_d_une_contrainte_d_inclusion]]
== Contrôle d'une contrainte d'inclusion

- Creation de la table jeu avec `idJeu` et `descriptionJeu`

- Creation de la table jeuinscriptions :

[source%linenums,css,indent=0]
----
CREATE TABLE jeuinscriptions (
    irefClient INT,
    dateInscription DATE,
    refJeu INT,
    FOREIGN KEY (refClient) REFERENCES client(idClient),
    FOREIGN KEY (refJeu) REFERENCES jeu(idJeu),
);
----

. Creation du trigger :

[source%linenums,css,indent=0]
----
BEGIN
    DECLARE command_count INT;

    SELECT COUNT(*) INTO command_count FROM commande WHERE client = NEW.refClient;

    IF command_count < 3 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Le client doit avoir au moins trois commandes.';
    END IF;
END
----

[[tp_fini]]
== Fin du tp


. `mysqldump -u root -p tp_procedures_stockees_bdd > tp_procedures_stockees_bdd.sql`

. `mysqldump -u root -p --routines --events tp_procedures_stockees_bdd > export_bdd_b.sql`

. `mysqldump -u root -p --no-create-info --no-data --no-create-db --routines --skip-triggers tp_procedures_stockees_bdd > export_procedures.sql`

. `CREATE USER 'mon_utilisateur'@'localhost' IDENTIFIED BY 'mot_de_passe';
GRANT ALL PRIVILEGES ON tp_procedures_stockees_bdd.* TO 'mon_utilisateur'@'localhost';
FLUSH PRIVILEGES;`

. `mysqldump -u root -p mysql user > users.sql`

. `mysqldump -u root -p --no-data mysql > export_users.sql`
